name: AdvPlots
main: com.empcraft.schem.Main
version: 2.3.0
load: STARTUP
description: A simple showcase of the advanced plot generation, merging control, and tessellation using the PlotSquared API.
authors: [Empire92, Citymonstret]
softdepend: [WorldEdit, PlotSquared]
database: false